# this is our development docker-compose building on top of the production docker-compose, just mounting
# the sync image and container names - not redefining anything else

version: "2"
services:
  tradingcloud:
    container_name: Trading_Cloud_App
    build: ./
    image: frostbyte07/btc-trading-app:latest

  #ciapp:
    #container_name: Jenkins_CI_APP
    #image: jenkins/jenkins
    #ports:
    #- 8080:8080
    #- 50000:50000

